version: "2"
name: sample-lambda
services:
  localstack:
    container_name: localstack
    hostname: localstack
    image: localstack/localstack:latest
    restart: unless-stopped
    ports:
      - 4566:4566
    volumes:
      - ./localstack-setup.sh:/etc/localstack/init/ready.d/script.sh
    networks:
      - local-net

  sample-lambda:
    container_name: sample-lambda
    hostname: sample-lambda
    build:
      dockerfile: Dockerfile
      context: ../
    environment:
      - ENVIRONMENT=local
      - DYNAMODB_HOST=http://host.docker.internal:7000
    restart: unless-stopped
    ports:
      - 8000:8000
    depends_on:
      - localstack
    networks:
      - local-net

networks:
  local-net:
